[settings]
go_set_gobin = false

[tools]
node = "24.11.1"
pnpm = "10"
npm = "latest"

"npm:gitmoji-cli" = "latest"
"ubi:goreleaser/goreleaser" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:sharkdp/bat" = "latest"
"npm:neovim" = "latest"
"npm:prettier" = "latest"
"npm:cspell" = "latest"
neovim = "latest"
python = "3.12"
fzf = "latest"
starship = "latest"
ghq = "latest"
lazygit = "latest"
delta = "latest"
zig = "latest"
gh = "latest"
go = "latest"
jq = "latest"
glab = "latest"

